### ISSUE TITLE
PPO stability issues with >1 process with Daily/CNN

### ISSUE THREAD

**Issue by Georgepu1** [CarperAI/trlx#324]
### 🐛 Describe the bug

Currently, the loss curve from training the Daily/CNN script (https://github.com/CarperAI/trlx/blob/main/examples/summarize_daily_cnn/t5_summarize_daily_cnn.py) has exploding loss when using 8 processes, and after changing it to 1 process, the loss curve has expected behavior (no loss explosion and stable training).

I know that previously running the GPT scripts with the summarize_rlhf directory uses 1 process for the PPO and 1 process for RM inference, but I'm confused why extending the number of processes causes an explosion in the loss value. My suspicion is that it could be due to a LR issue/normalization, but I'm wondering if anyone has faced this before and if there's any resolution to utilize >1 process for PPO?

If anyone has any recommendations on next steps that'd be greatly appreciated, and I'll attach screenshots of the loss curves below. Thanks!

<img width="1151" alt="Screen Shot 2023-02-21 at 2 14 08 PM" src="https://user-images.githubusercontent.com/45472546/220470636-171b2f65-aadd-4108-92e4-27269fbfbfb7.png">

<img width="1154" alt="Screen Shot 2023-02-21 at 2 14 29 PM" src="https://user-images.githubusercontent.com/45472546/220470689-678f02c9-2ffe-48a8-b0d5-4b766587aecd.png">

**Comment by jboboyle** [comment]
I've been running into a similar issue, though the instability in policy loss remains when using single process. Not sure what is causing such a large difference between the current and old logprobs.  
![image](https://user-images.githubusercontent.com/74334014/220477031-1e2ae632-5196-402f-8e3d-badd2eb4b627.png)

**Comment by PhungVanDuy** [comment]
Can you share your accelerate configure?

**Comment by Georgepu1** [comment]
Yup, thanks for helping:

WANDB: https://api.wandb.ai/links/georgepu/wajmtmoz

```
compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_accumulation_steps: 1
  offload_optimizer_device: cpu
  offload_param_device: cpu
  zero3_init_flag: false
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
machine_rank: 0
main_training_function: main
megatron_lm_config: {}
mixed_precision: bf16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
use_cpu: false
```
