### ISSUE TITLE
Deadlock (nothing happening) in multi-GPU setting

### ISSUE THREAD

**Issue by ayulockin** [CarperAI/trlx#34]
Hey all, I am using this [colab notebook](https://colab.research.google.com/drive/1LWz_0xtH4OPkRytO34sdyZTqI4K52njY?usp=sharing#scrollTo=SoNdzrJLfCo-) as a reference (that I found in the discord server) to train `examples/ppo_sentiments.py` using HF Accelerate in a GCP VM with 2 K80s. 

This is my `accelerate config`:

```
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
downcast_bf16: 'no'
fsdp_config: {}
gpu_ids: '[all]'
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
use_cpu: false
```

Unfortunately, nothing happens after this point, as shown in the image:

<img width="941" alt="image" src="https://user-images.githubusercontent.com/31141479/196096788-b45f637a-d658-4fa4-a99c-b39ec391e411.png">

To avoid getting this warning, `huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...`, I set `TOKENIZERS_PARALLELISM=false`.  

I am not an expert in using Accelerate; any help would be appreciated. Also, for context, I am trying to run this example to build W&B sweeps (hyperparameter optimization), mentioned in #12.

cc: @LouisCastricato

**Comment by LouisCastricato** [comment]
@Dahoas @reciprocated

**Comment by reciprocated** [comment]
Can reproduce this. `gpu_ids: '[all]'` in the config doesn't put anything on gpu. So it's not a deadlock, but rather the training on cpu is progressing very slowly. Interesting to see which version of accelerate have you used to generate this config. Correct version on 0.13.0 is `gpu_ids: all` or removing the line altogether. However I also uncovered that our ddp intergration is lacking in another way, I'll have a separate issue for that, in the meantime if you want multigpu here's the config which works on this example:
```
compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero_stage: 1
distributed_type: DEEPSPEED
downcast_bf16: 'no'
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 2
use_cpu: false
```

And just in case you don't have to burn gcp credits to test sweeps, since you can run examples without accelerate's launchers and also locally on cpu if you don't expect the training to complete. Good luck!
