### ISSUE TITLE
when training large GPT model(10B+) with deepspeed zero3, the model generate can be very slow.

### ISSUE THREAD

**Issue by Hunter-P** [CarperAI/trlx#347]
### 🐛 Describe the bug
 These are my deepspeed config:

```
deepspeed_config:
  deepspeed_multinode_launcher: standard
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero_stage: 3
```
I can't use zero_stage:2 because the model is too large, but when the zero_stage is set to 3, model generate will be extremely slow, I have no idea about this, and is there any solution?
